package Java_Exception_Handling;

public class MultipleCatchDemo4 {

    public static void main(String[] args) {

        /*we do not maintain the order of preference in exceptions (child to parent),
        then compile time error occurs.*/

//        try {
//            int a[] = new int[10];
//            System.out.println(a[10]);
//
//        } catch (Exception e) {
//            System.out.println("Parent Exception occurs");
//
//        } catch (ArithmeticException e) {
//            System.out.println("Arithmetic Exception occurs");
//
//        } catch (ArrayIndexOutOfBoundsException e) {
//            System.out.println("ArrayIndexOutOfBounds Exception occurs");
//
//        }
        System.out.println("Rest of the program");
    }
}
